// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvJ9lLRAIJuTgzDVQNkl_FxS7bVLWipRg',
    appId: '1:141868410312:web:f6faa451d0ec42e998ccfd',
    messagingSenderId: '141868410312',
    projectId: 'portifolio-cfd43',
    authDomain: 'portifolio-cfd43.firebaseapp.com',
    storageBucket: 'portifolio-cfd43.appspot.com',
    measurementId: 'G-BBBKJ6S74W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhYmyaoHn9zs8y0Pbi58bFyvQosb7sS8s',
    appId: '1:141868410312:android:26c06d988e12c3f598ccfd',
    messagingSenderId: '141868410312',
    projectId: 'portifolio-cfd43',
    storageBucket: 'portifolio-cfd43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2O9kYtzDDDOkfnxxjM1REXLzdBlo4IkQ',
    appId: '1:141868410312:ios:93c4bfb7a2946ec798ccfd',
    messagingSenderId: '141868410312',
    projectId: 'portifolio-cfd43',
    storageBucket: 'portifolio-cfd43.appspot.com',
    iosClientId: '141868410312-0aneb796ksp8ekulfcnl8lfm6k22c034.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2O9kYtzDDDOkfnxxjM1REXLzdBlo4IkQ',
    appId: '1:141868410312:ios:93c4bfb7a2946ec798ccfd',
    messagingSenderId: '141868410312',
    projectId: 'portifolio-cfd43',
    storageBucket: 'portifolio-cfd43.appspot.com',
    iosClientId: '141868410312-0aneb796ksp8ekulfcnl8lfm6k22c034.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
